### ISSUE TITLE
Writing metadata via command line?

### ISSUE THREAD

**Issue by zachstultz** [ajslater/comicbox#55]
Maybe I'm doing something wrong, I was checking out the command line instructions and trying to test out writing ComicInfo tags to a file, but I'm not having any luck. 

(just an fyi, I did see the previous closed issue similar to mine, but it was from almost two years ago and had the conclusion of it not being supported at the time, I assume with this option, it is now?)

```
comicbox test.cbz -m "Tags=test1,test2,test3"

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/comicbox", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/comicbox/cli.py", line 161, in main
    args = get_args(params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/comicbox/cli.py", line 155, in get_args
    cns = parser.parse_args(params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1824, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1857, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2066, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2006, in consume_optional
    take_action(action, args, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1934, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/comicbox/cli.py", line 13, in __call__
    values = dict(item.split("=") for item in values.split(",")) if values else 
    ```

**Comment by ajslater** [comment]
Well that crash is a bug, but the writing of tags from the command line was never really implemented.
I think I will implement it though, because of this report.
Probably the next version of comicbox will happen within a week and include writing comic metadata into archives from the cli.

**Comment by ajslater** [comment]
Comicbox v0.10.0 now supports writing metadata from the command line. The CLI options have changed a bit, possibly in a breaking way for some uses. Check the cli help.

```sh
comicbox test.cbz -m "Tags=a,b,c" -m "Publisher=SmallComics" -w cr
```

will write those tags to comicinfo.xml in the archive.
